add new scripts

diff --git a/lab-1/script-4 b/lab-1/script-4
--- a/lab-1/script-4
+++ b/lab-1/script-4
@@ -1,11 +1,11 @@
 #!/bin/bash
 
-echo "1) nano"
-echo "2) vi"
-echo "3) links"
-echo "4) exit"
-
-read s
-if [[ "$s" == "1" ]]
-then "nano"
+if [[ "$HOME" == "$PWD" ]];
+then
+	echo "$HOME"
+	exit 0
 fi
+
+echo "ERROR"
+exit 1
+
